
#STAGE 1 : This is the Java enabled Linux Apline base Docker image
FROM openjdk:17-jdk-alpine

#STAGE 2 : Add Spring Boot Executible JAR to the Java Base Image
COPY  target/portal-boot.jar ./portal.jar

#STAGE 3 - Set up the run options, make port available to world outside the container
EXPOSE 80
EXPOSE 5000
EXPOSE 8443

ENTRYPOINT [ "java", "-jar", "portal.jar"]






# 6-27 test 2
#VOLUME ./mnt/efs_data /mnt/efs_data  /efs efs
# 6-24-2022
#tried without the dot, and throws can make the directory error
#RUN mkdir -p ./mnt/efs_data
#RUN mkdir -p ./efs
#VOLUME /efs ./mnt/efs_data efs
# 6-27 test 1, task wont start
#VOLUME .  /efs  /mnt/efs_data

#RUN mkdir -p ./mnt/efs_data
#WORKDIR /
# 6-27 test 3
#VOLUME ["/mnt/efs_data","/efs", "/efs/mnt/efs_data", "/"]