##########    5-10-2024
drop TABLE locuslink.assembly_ai_status
drop TABLE locuslink.assembly_attachment 
drop TABLE locuslink.assembly_req_docs 
drop TABLE locuslink.assembly 

CREATE TABLE "assembly" (
  "assembly_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
  "manufacturer_pkid" int,
  "customer_pkid" int,    
  "job_number" varchar, 
  "job_description" varchar, 
  "location" varchar,     
  "station_number" varchar, 
  "trace_number" varchar,   
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "assembly_req_docs" (
  "ard_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "assembly_pkid" int,
  "doc_type_pkid" int,  
  "doc_description" varchar not null,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);


CREATE TABLE "assembly_attachment" (
  "aa_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
  "assembly_pkid" int,
  "doc_type_pkid" int,  
  "filename_fullpath" varchar,
  "attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "assembly_ai_status" (
  "aais_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "aa_pkid" int, 
  "status_type" varchar not null,
  "status" varchar not null,
  "status_description" varchar not null,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

ALTER TABLE "assembly_req_docs" ADD CONSTRAINT "fk_ard_assembly" FOREIGN KEY ("assembly_pkid") REFERENCES "assembly" ("assembly_pkid");
ALTER TABLE "assembly_req_docs" ADD CONSTRAINT "fk_ard_doctype" FOREIGN KEY ("doc_type_pkid") REFERENCES "document_type" ("doc_type_pkid");
ALTER TABLE "assembly_attachment" ADD CONSTRAINT "fk_aa_assembly" FOREIGN KEY ("assembly_pkid") REFERENCES "assembly" ("assembly_pkid");
ALTER TABLE "assembly_attachment" ADD CONSTRAINT "fk_aa_doctype" FOREIGN KEY ("doc_type_pkid") REFERENCES "document_type" ("doc_type_pkid");
ALTER TABLE "assembly_ai_status" ADD CONSTRAINT "fk_aais_aa" FOREIGN KEY ("aa_pkid") REFERENCES "assembly_attachment" ("aa_pkid");

ALTER TABLE "assembly" ADD CONSTRAINT "fk_a_cust" FOREIGN KEY ("customer_pkid") REFERENCES "customer" ("customer_pkid");
ALTER TABLE "assembly" ADD CONSTRAINT "fk_a_mfg" FOREIGN KEY ("manufacturer_pkid") REFERENCES "manufacturer" ("manufacturer_pkid");

#############################################################################

alter table user_locuslink  ADD COLUMN email_address varchar;

alter table user_locuslink  ADD COLUMN phone_number varchar;



##### code bug but still, i dont want dups in the product attribute, it causes SQL to return dups in the UI
alter table Product_Attribute
add constraint UK_pa unique (ucat_pkid);

##########    11-14-2023
CREATE TABLE "catalog_req_docs" (
  "crd_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ucat_pkid" int,
  "doc_type_pkid" int,  
  "docDescription" varchar not null,    
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);
ALTER TABLE "catalog_req_docs" ADD CONSTRAINT "fk_crd_ucat" FOREIGN KEY ("ucat_pkid") REFERENCES "universal_catalog" ("ucat_pkid");
ALTER TABLE "catalog_req_docs" ADD CONSTRAINT "fk_crd_doctype" FOREIGN KEY ("doc_type_pkid") REFERENCES "document_type" ("doc_type_pkid");

CREATE TABLE "asset_req_docs" (
  "ard_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
  "unique_asset_pkid" int,  
  "doc_type_pkid" int,  
  "docDescription" varchar not null,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);
ALTER TABLE "asset_req_docs" ADD CONSTRAINT "fk_ard_attach" FOREIGN KEY ("doc_type_pkid") REFERENCES "document_type" ("doc_type_pkid");
ALTER TABLE "asset_req_docs" ADD CONSTRAINT "fk_ard_ua" FOREIGN KEY ("unique_asset_pkid") REFERENCES "unique_asset" ("unique_asset_pkid");


CREATE TABLE "catalog_attachment" (
  "ca_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
  "ucat_pkid" int,
  "doc_type_pkid" int,
  "filename_fullpath" varchar,
  "attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);
ALTER TABLE "catalog_attachment" ADD CONSTRAINT "fk_ca_ucat" FOREIGN KEY ("ucat_pkid") REFERENCES "universal_catalog" ("ucat_pkid");
ALTER TABLE "catalog_attachment" ADD CONSTRAINT "fk_ca_doctype" FOREIGN KEY ("doc_type_pkid") REFERENCES "document_type" ("doc_type_pkid");

######################################


CREATE TABLE "user_role_type" (
  "user_role_type_pkid" INT PRIMARY KEY,  
  "userRoleCode" varchar not null,
  "userRoleDesc" varchar not null,
   
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);


CREATE TABLE "user_membership" (
  "user_membership_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
  "user_locuslink_pkid" int not null,
  "user_role_type_pkId" int not null,   
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);
ALTER TABLE "user_membership" ADD CONSTRAINT "fk_um_user" FOREIGN KEY ("user_locuslink_pkid") REFERENCES "user_locuslink" ("user_locuslink_pkid");
ALTER TABLE "user_membership" ADD CONSTRAINT "fk_um_userroletype" FOREIGN KEY ("user_role_type_pkid") REFERENCES "user_role_type" ("user_role_type_pkid");



CREATE TABLE "universal_cat_selected_attributes" (
  "ucat_selected_attributes__pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  "ucat_pkid" int not null,
  "cdugt_pkid" int not null,
   
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);


ALTER TABLE "universal_cat_selected_attributes" ADD CONSTRAINT "fk_ucsa_uc" FOREIGN KEY ("ucat_pkid") REFERENCES "universal_catalog" ("ucat_pkid");
ALTER TABLE "universal_cat_selected_attributes" ADD CONSTRAINT "fk_ucsa_cdugt" FOREIGN KEY ("cdugt_pkid") REFERENCES "catalog_def_uid_gen_tpl" ("cdugt_pkid");



CREATE TABLE "catalog_def_uid_gen_tpl" (
  "cdugt_pkid" int PRIMARY KEY,
  
  "industry_pkid" int not null,
  "sub_industry_pkid" int not null,  
  "product_type_pkid" int not null,
  "product_sub_type_pkid" int NULL,  
  
  "uid_template" varchar,
  "uid_template_len" int not NULL, 
 
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

ALTER TABLE "catalog_def_uid_gen_tpl" ADD CONSTRAINT "fk_cdugt_i" FOREIGN KEY ("industry_pkid") REFERENCES "industry" ("industry_pkid");
ALTER TABLE "catalog_def_uid_gen_tpl" ADD CONSTRAINT "fk_cdugt_si" FOREIGN KEY ("sub_industry_pkid") REFERENCES "sub_industry" ("sub_industry_pkid");
ALTER TABLE "catalog_def_uid_gen_tpl" ADD CONSTRAINT "fk_cdugt_pt" FOREIGN KEY ("product_type_pkid") REFERENCES "product_type" ("product_type_pkid");
ALTER TABLE "catalog_def_uid_gen_tpl" ADD CONSTRAINT "fk_cdugt_pst" FOREIGN KEY ("product_sub_type_pkid") REFERENCES "product_sub_type" ("product_sub_type_pkid");


CREATE TABLE "catalog_def_attr_list" (
  "cdal_pal_pkid" int PRIMARY KEY,  
  "cdugt_pkid" int not null,  
  
  "uid_attr_seq" int not NULL, 
  "uid_attr_list_name" varchar,
  "uid_attributes_json" varchar,
 
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

ALTER TABLE "catalog_def_attr_list" ADD CONSTRAINT "fk_cdal_cdugt" FOREIGN KEY ("cdugt_pkid") REFERENCES "catalog_def_uid_gen_tpl" ("cdugt_pkid");







CREATE TABLE "industry" (
  "industry_pkid" int PRIMARY KEY,
  "uid" varchar,
  "industry_code" varchar,
  "industry_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "sub_industry" (
  "sub_industry_pkid" int PRIMARY KEY,
   "industry_pkid" int,
   "uid" varchar,      
  "sub_industry_code" varchar,
  "sub_industry_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "product_type" (
  "product_type_pkid" int PRIMARY KEY,
   "sub_industry_pkid" int,
  "uid" varchar,   
  "type_code" varchar,
  "type_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "product_sub_type" (
  "product_sub_type_pkid" int PRIMARY KEY,
  "product_type_pkid" int,
  "uid" varchar,   
  "sub_type_code" varchar,
  "sub_type_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);


CREATE TABLE "product_type_gs1" (
  "product_type_gs1_pkid" int PRIMARY KEY,
  "product_type_pkid" int,
  "gs1_ai" int,
  "gs1_dataName" varchar,
  "gs1_barcodeLabel" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);


CREATE TABLE "document_type" (
  "doc_type_pkid" int PRIMARY KEY,
  "doc_type_code" varchar,
  "doc_type_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "universal_catalog" (
  "ucat_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universal_catalog_id" varchar,  
--  "uid_pal_pkid" int,  
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);



CREATE TABLE "product_template" (
  "product_template_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ucat_pkid" int,
  "product_template_desc" varchar,
  "unique_attributes_json" varchar,
  "additional_attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "product_attribute" (
  "product_attr_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ucat_pkid" int,
   "attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "product_attachment" (
  "product_attach_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unique_asset_pkid" int,
  "doc_type_pkid" int,
  "filename_fullpath" varchar,
  "attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "manufacturer" (
  "manufacturer_pkid" int PRIMARY KEY,
  "name" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "traceability_type" (
  "traceability_type_pkid" int PRIMARY KEY,
  "traceability_type_code" varchar,
  "traceability_type_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "unique_asset" (
  "unique_asset_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unique_asset_id" varchar,
  "ucat_pkid" int,
  "manufacturer_pkid" int,
  "customer_pkid" int,    
  "traceability_type_pkid" int,
    
  "trace_code" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "asset_published" (
  "asset_published_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unique_asset_pkid" int,
  "published_date" timestamp,
  "active_flag" varchar,
  "comment" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "purchase_order" (
  "po_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_pkid" int,
  "project_pkid" int,
  "po_date" timestamp,
  "po_number" varchar,
  "po_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "purchase_order_line" (
  "po_line_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "po_pkid" int,
  "unique_asset_pkid" int,
  "po_line_number" varchar,
  "po_line_desc" varchar,
  "add_by" varchar,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "customer" (
  "customer_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_type_code" varchar,
  "customer_name" varchar,
  "active_flag" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "project" (
  "project_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_pkid" int,
  "project_type_code" varchar,
  "project_name" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "user_locuslink" (
  "user_locuslink_pkid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_type_code" varchar,
  "login_name" varchar,
  "first_name" varchar,
  "last_name_bus_name" varchar,
  "active_flag" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);




ALTER TABLE "product_type" ADD CONSTRAINT "fk_pt_si" FOREIGN KEY ("sub_industry_pkid") REFERENCES "sub_industry" ("sub_industry_pkid");

ALTER TABLE "sub_industry" ADD CONSTRAINT "fk_si_i" FOREIGN KEY ("industry_pkid") REFERENCES "industry" ("industry_pkid");

ALTER TABLE "product_sub_type" ADD CONSTRAINT "fk_pst_pt" FOREIGN KEY ("product_type_pkid") REFERENCES "product_type" ("product_type_pkid");


ALTER TABLE "product_template" ADD CONSTRAINT "fk_ptemplate_pt" FOREIGN KEY ("ucat_pkid") REFERENCES "universal_catalog" ("ucat_pkid");

ALTER TABLE "product_attribute" ADD CONSTRAINT "fk_pa_ucat" FOREIGN KEY ("ucat_pkid") REFERENCES "universal_catalog" ("ucat_pkid");

ALTER TABLE "product_type_gs1" ADD CONSTRAINT "fk_ptgs1_pt" FOREIGN KEY ("product_type_pkid") REFERENCES "product_type" ("product_type_pkid");




ALTER TABLE "product_attachment" ADD CONSTRAINT "fk_dt_attach" FOREIGN KEY ("doc_type_pkid") REFERENCES "document_type" ("doc_type_pkid");

ALTER TABLE "product_attachment" ADD CONSTRAINT "fk_attach_ua" FOREIGN KEY ("unique_asset_pkid") REFERENCES "unique_asset" ("unique_asset_pkid");

ALTER TABLE "unique_asset" ADD CONSTRAINT "fk_ua_ucat" FOREIGN KEY ("ucat_pkid") REFERENCES "universal_catalog" ("ucat_pkid");

ALTER TABLE "unique_asset" ADD CONSTRAINT "fk_ua_tt" FOREIGN KEY ("traceability_type_pkid") REFERENCES "traceability_type" ("traceability_type_pkid");

ALTER TABLE "unique_asset" ADD CONSTRAINT "fk_ua_cust" FOREIGN KEY ("customer_pkid") REFERENCES "customer" ("customer_pkid");

ALTER TABLE "unique_asset" ADD CONSTRAINT "kucat_mfg" FOREIGN KEY ("manufacturer_pkid") REFERENCES "manufacturer" ("manufacturer_pkid");

ALTER TABLE "asset_published" ADD CONSTRAINT "fk_pa_ua" FOREIGN KEY ("unique_asset_pkid") REFERENCES "unique_asset" ("unique_asset_pkid");

ALTER TABLE "purchase_order" ADD CONSTRAINT "fk_po_proj" FOREIGN KEY ("project_pkid") REFERENCES "project" ("project_pkid");

ALTER TABLE "purchase_order_line" ADD CONSTRAINT "fk_pol_po" FOREIGN KEY ("po_pkid") REFERENCES "purchase_order" ("po_pkid");

ALTER TABLE "purchase_order_line" ADD CONSTRAINT "fk_po_ua" FOREIGN KEY ("unique_asset_pkid") REFERENCES "unique_asset" ("unique_asset_pkid");

ALTER TABLE "project" ADD CONSTRAINT "fk_project_customer" FOREIGN KEY ("customer_pkid") REFERENCES "customer" ("customer_pkid");
