CREATE TABLE "manufacturer" (
  "manufacturer_id" int PRIMARY KEY,
  "name" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "material_item_type" (
  "mat_item_type_id" int PRIMARY KEY,
  "type_code" varchar,
  "type_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "material_test_type" (
  "mat_test_type_id" int PRIMARY KEY,
  "type_code" varchar,
  "type_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "material_test" (
  "mat_test_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mat_test_type_id" int,
  "mat_item_id" int,
  "test_desc" varchar,
  "attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "material_item_attribute" (
  "mat_item_attr_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mat_item_id" int,
  "attributes_json" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "material_item" (
  "mat_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mat_item_type_id" int,
  "manufacturer_id" int,
  "mat_item_num" varchar,
  "model_num" varchar,
  "item_desc" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

CREATE TABLE "user_locuslink" (
  "user_locuslink_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_type_code" varchar,
  "login_name" varchar,
  "first_name" varchar,
  "last_name_bus_name" varchar,
  "active_flag" varchar,
  "add_by" varchar,
  "add_ts" timestamp,
  "update_by" varchar,
  "update_ts" timestamp
);

ALTER TABLE "material_test" ADD CONSTRAINT "fk_mt_mtt" FOREIGN KEY ("mat_test_type_id") REFERENCES "material_test_type" ("mat_test_type_id");

ALTER TABLE "material_test" ADD CONSTRAINT "fk_mt_mi" FOREIGN KEY ("mat_item_id") REFERENCES "material_item" ("mat_item_id");

ALTER TABLE "material_item_attribute" ADD CONSTRAINT "fk_mia_mi" FOREIGN KEY ("mat_item_id") REFERENCES "material_item" ("mat_item_id");

ALTER TABLE "material_item" ADD CONSTRAINT "fk_mi_manufacturer" FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturer" ("manufacturer_id");

ALTER TABLE "material_item" ADD CONSTRAINT "fk_mi_mit" FOREIGN KEY ("mat_item_type_id") REFERENCES "material_item_type" ("mat_item_type_id");
