# This workflow will Deploy an image pulled from the GHCR, using a build number input by the user

name: Deploy Docker Image - AWS Dev

on: 
  workflow_dispatch:
    inputs:
      buildnumber:
        description: Input the Build Run Number to deploy
        default: 0
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  
  AWS_REGION: ap-south-1                   
  ECR_REPOSITORY: demo-repo        
  ECS_SERVICE: demo-service               
  ECS_CLUSTER: demo-ecs-cluster              
  ECS_TASK_DEFINITION: .aws/td.json 
  CONTAINER_NAME: nginx
  
  BUILD_NUMBER :  ${{ inputs.buildnumber }}
  #BUILD_SOURCE_ENV: dev
  BUILD_TARGET_ENV: dev    #dev,test,prod
  
jobs:

 deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Pull the Docker Image
      run: |      
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
              
        echo IMAGE_ID=$IMAGE_ID        
        echo GITHUB_RUN_ID=${GITHUB_RUN_ID}        
        echo BUILD_NUMBER=$BUILD_NUMBER
        echo BUILD_SOURCE_ENV=$BUILD_SOURCE_ENV
        echo BUILD_TARGET_ENV=$BUILD_TARGET_ENV

        #docker tag $IMAGE_NAME $IMAGE_ID:${GITHUB_RUN_NUMBER}.$VERSION
        #docker push $IMAGE_ID:${GITHUB_RUN_NUMBER}.$VERSION          
        #docker pull $IMAGE_ID:2.dev
        
        docker pull $IMAGE_ID:$BUILD_NUMBER.$BUILD_SOURCE_ENV
