# This workflow will:
#        - pull the Docker Image in the GHCR Git Hub Container Registry, using the build number provided as a parameter  xxxxxxxxxx.dev.4 
#        - push the Docker Image in the GHCR Git Hub Container Registry, xxxxxxxxxx.dev.4.latest  {for reference for redeploy, backout, etc} 
#        - push the Docker Image in the GHCR Git Hub Container Registry, xxxxxxxxxx.dev.latest   {used by the ECS container}
#        - update the AWS Cluster & Service, will will repull the Docker Inmage by name convention, xxxxxxxxx.dev.latest

name: Deploy AWS Dev

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Build Number to Deploy'
        required: true
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  AWS_REGION: us-east-1      
  ECS_CLUSTER: sparks-default-cluster   
  ECS_SERVICE: container-sparks-service                          
  CONTAINER_NAME: container-sparks
  
  BUILD_NUMBER :  ${{ inputs.buildnumber }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

   # - name: Extract metadata (tags, labels) for Docker
   #   id: meta
   #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
   #   with:
   #       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
    - name: Pull and Re-Store the Docker Image as the LATEST for this environment
      run: |      
        IMAGE_ID=ghcr.io/$IMAGE_NAME
              
        echo IMAGE_ID=$IMAGE_ID        
        echo GITHUB_RUN_ID=${GITHUB_RUN_ID}        
        echo BUILD_NUMBER=$BUILD_NUMBER
        echo BUILD_SOURCE_ENV=$BUILD_SOURCE_ENV
        echo BUILD_TARGET_ENV=$BUILD_TARGET_ENV

        #docker tag $IMAGE_NAME $IMAGE_ID:$VERSION.${GITHUB_RUN_NUMBER}
        #docker push $IMAGE_ID:$VERSION.${GITHUB_RUN_NUMBER}
        
        # pull the one we want to deploy
        docker pull $IMAGE_ID:$VERSION.${GITHUB_RUN_NUMBER}     
        
        # push the build number as build.latest for reference and DR, and redeploy
        docker push $IMAGE_ID:$VERSION.${GITHUB_RUN_NUMBER}.latest
        
         # push as latest for AWS ECS configuration
        docker push $IMAGE_ID:$VERSION.latest

