# This workflow will:
#        - pull the Docker Image in the GHCR Git Hub Container Registry, using the build number provided as a parameter  xxxxxxxxxx.dev.4 
#        - push the Docker Image in the GHCR Git Hub Container Registry, xxxxxxxxxx.dev.4.latest  {for reference ro redeploy, backout, etc} 
#        - push the Docker Image in the GHCR Git Hub Container Registry, xxxxxxxxxx.dev.latest   {used by the ECS container}
#        - update the AWS Cluster & Service, will will repull the Docker Inmage by name convention, xxxxxxxxx.dev.latest

name: Deploy AWS Dev

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  AWS_REGION: us-east-1                   
  ECR_REPOSITORY: ghcr.io/sparxtec-locuslink/sparxtec-locuslink/locuslink:3.dev        
  ECS_SERVICE: container-sparks-service               
  ECS_CLUSTER: sparks-default-cluster              
  ECS_TASK_DEFINITION: first-run-task-definition:2 
  CONTAINER_NAME: container-sparks
  
  BUILD_NUMBER :  ${{ inputs.buildnumber }}
  #BUILD_SOURCE_ENV: dev
  BUILD_TARGET_ENV: dev    #dev,test,prod
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            
    - name: Store the Docker Image
      run: |      
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
              
        echo IMAGE_ID=$IMAGE_ID        
        echo GITHUB_RUN_ID=${GITHUB_RUN_ID}        
        echo BUILD_NUMBER=$BUILD_NUMBER
        echo BUILD_SOURCE_ENV=$BUILD_SOURCE_ENV
        echo BUILD_TARGET_ENV=$BUILD_TARGET_ENV

        #docker tag $IMAGE_NAME $IMAGE_ID:${GITHUB_RUN_NUMBER}.$VERSION
        #docker push $IMAGE_ID:${GITHUB_RUN_NUMBER}.$VERSION          
        #docker pull $IMAGE_ID:2.dev
        
        docker pull $IMAGE_ID:$BUILD_NUMBER.$BUILD_SOURCE_ENV        

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
